### ISSUE TITLE
nvl setup throws SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by ikb42** [anvilresearch/connect-cli#51]
Windows:

C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:75
    throw e;
          ^
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.inquirer.prompt.prompts.input.render (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\lib\plugins\prompt.js:440:17)
    at Prompt._run (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\prompts\input.js:49:8)
    at Prompt.run (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
    at setDisposable (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe](C:UsersIvanAppDataRoamingnpmnode_modulesanvil-connect-clinode_modulesinquirernode_modulesrx-literx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:2112:21)
    at AnonymousObservable.tryCatcher (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
    at setDisposable (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe](C:UsersIvanAppDataRoamingnpmnode_modulesanvil-connect-clinode_modulesinquirernode_modulesrx-literx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1604:19)
    at MergeObserver.handleSubscribe (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:2910:28)
    at MergeObserver.onNext (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:2916:16)
    at MergeObserver.tryCatcher (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\Ivan\AppData\Roaming\npm\node_modules\anvil-connect-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5782:51)

**Comment by christiansmith** [comment]
Appears to be an issue with a [dependency](https://github.com/Reactive-Extensions/RxJS) of a [dependency](https://github.com/sboudrias/Inquirer.js). 

Just a note, @ikb42, you can expect to run into other issues like this on Windows, since we don't yet officially support it. PRs are very welcome if you're able to sort it out yourself.

**Comment by adalinesimonian** [comment]
@ikb42 Can you provide the input you entered into `nvl setup`, minus any confidential and/or personal details?

Also, when did this error occur? After a certain question? At the start of the command?

**Comment by ikb42** [comment]
No input, just `nvl setup`, enter, and then bang.

**Comment by adalinesimonian** [comment]
@ikb42 It looks like the problem is that Inquirer is unable to obtain the CLI width, and tries to construct an invalid regular expression as a result. I've gone ahead and [reported it on the Inquirer repository](https://github.com/SBoudrias/Inquirer.js/issues/290).

**Comment by christiansmith** [comment]
Thanks @vsimonian!
